### PR TITLE
Switch from aufs to overlayfs for the docker storage driver

### PR DESCRIPTION
**Pull request by michal-mazurek**
* overlay2 doesn't work yet, see FD discussion
* This PR depends on a newer meta-resin version

So don't merge yet.

### CODE REVIEW

**Comment by michal-mazurek** [comment]
connect https://github.com/resin-os/resin-chip/issues/18

**Review by agherzan — CHANGES_REQUESTED** [review]
Isn't changelog needed?

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@michal-mazurek please add a Changelog entry too

**Comment by michal-mazurek** [comment]
This board hasn't been released yet, who would use the changelog?

**Comment by floion** [comment]
True also :)

**Pull request merged**
